apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet
  labels:
    app: pet
spec:
  replicas: 1
  template:
    metadata:
      name: pet
      labels:
        app: pet
    spec:
      containers:
        - name: pet
          image: zrimmyjr/pet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: pet